name: Docker Compose CI

on: [push]

env:
  TZ: ${{ secrets.TZ }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose.yml
      run: docker-compose build
