name: docker-compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TZ: ${{ secrets.TZ }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose.yml
      run: docker-compose build
