name: php-cs-fixer

on: pull_request

jobs:
  fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
        chmod a+x php-cs-fixer
    - name: execute fixer
      run: php php-cs-fixer fix ./src --dry-run
