name: php-cs-fixer

on: [push, pull_request]

jobs:
  fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: composer install

    - name: execute fixer
      run: ./vendor/bin/php-cs-fixer fix ./ --dry-run
